package replaydriver;

// generated by LEAP on Sat Oct 12 22:32:53 CST 2013
// Created for XXX JVM: 11.2-b01
import edu.hkust.leap.tracer.*;
import edu.hkust.leap.replayer.*;

public class ReplayDriver {

	public static void setUp() throws Exception {
		TraceReader.readTrace(1,"/home/qingkai/Swan/Swan-2.0/Leap-Recorder/tmp/Leap3588180034053044873_accessVector.trace.gz");
		TraceReader.readTrace(2,"/home/qingkai/Swan/Swan-2.0/Leap-Recorder/tmp/Leap3588180034053044873_threadNameToIdMap.trace.gz");
		TraceReader.readTrace(3,"/home/qingkai/Swan/Swan-2.0/Leap-Recorder/tmp/Leap3588180034053044873_nanoTimeDataVec.trace.gz");
		TraceReader.readTrace(4,"/home/qingkai/Swan/Swan-2.0/Leap-Recorder/tmp/Leap3588180034053044873_nanoTimeThreadVec.trace.gz");
	}

	public static void main(String[] args) throws Throwable {

		setUp();

		new Thread("leap-main"){
			public void run(){
				// load arguments
				String[] mainargs = {};
				try {
					example.Example.main(mainargs);
				} catch (Throwable e) {
					e.printStackTrace();
				}
			}
		}.start();

		(new Scheduler()).start();

		//WAIT FOR 1 MINUTE TO STOP REPLAY
		//Thread.currentThread().sleep(60000);
	}
}

